# ###############################
# ######## EASYFIREWORK #########
# ### BY ANGESCHOSSEN@YouTube ###
# ###############################
# ###### EXPLANATION ABOUT ######
# ----- EVERY CONFIGURATION -----
# ### YOU CAN FIND ON GITHUB ####
# ########## SPIGOTMC ###########
# ###############################


# General settings
General:
  # Delay to start the firework with /Ef start or automatically
  # type: int
  DelayStart: 10
  # Time interval between every firework rocket
  # Set it to 0, if you don't want that
  # type: int
  TimeInterval: 20
  # True: Starts the firework, if it exists, automatically after enabling the plugin
  # False: Don't start a firework after enabling the plugin
  # type: boolean
  AutoStart: true
  # Option to stop a firework after it started
  # You can set a delay
  AutoStop:
    # Enable it? True or false
    # type: boolean
    Enabled: true
    # Set the minutes you want
    # type: int
    Minutes: 1
    # Configurate this option
    # Where should it be used?
    Objects: 
      # If you use /EasyFirework start
      # type: boolean
      StartCommand: true
      # When the server restarts or is reloaded
      # type: boolean
      AutoStart: true
      # See RealTime option below
      # type: boolean
      RealTime: true  
# You can set a date when the firework should start
RealTime:
  # Enable it? True or false
  # type: boolean
  Enabled: true
  # There are two date formats. British and american
  # British means Day-Month-Year
  # American means Month-Day-Year
  # Very important for the following option "Start date"
  # It will use british if you don't set any of them
  # type: string
  DateFormat: british
  # Set your date
  # Replace only the numbers. Don't touch the other characters!
  # type: string
  StartDate: 01-01-2017 00:00
  # This message will be shown every player and to the console when it reaches the date, wich you set
  Message: '&6Easy Firework wish you all a happy new year!'
  # Here you can add a sound, wich will be played to every player, when it reaches the date
  Sound:
    # Enable it? True or false
    # type: boolean
    Enable: true
    # Set your sound
    # You can find all aviable sounds here: https://www.spigotmc.org/wiki/cc-sounds-list/
    # type: string
    Sound: ENTITY_PLAYER_LEVELUP
# Set the a time (in ticks) when firework starts
AutoTime:
  # Enable it? True or false
  # type: boolean
  Enable: true
  # Set the time in ticks
  # 18000 is midnight
  Ticks: 18000
  # The plugin will get your worlds automatically
  # Set true to set AutoTime enabled in this world
  # Set false to enable it in the world
  Worlds:
    world: true
    world_nether: true
    world_the_end: true
