# General settings
firework:
  # Interval between firework spawns
  # You can add parameters like h(hours), m(minutes), s(seconds)
  # Example: 5s
  interval: 5s
  # Firework start delay
  delay: 1s
  # Ingame map time
  # Set it to 0, if you dont want it
  time: 13000
# Autostop delay
# Stops firework after it started
# Set it to 0, if you dont want it
autostop:
  # You can add parameters like h(hours), m(minutes), s(seconds)
  # Example: 5m
  # Set it to 0, if you dont want it
  delay: 5m
# Autostart options
autostart:
  # List fireworks wich should started automatically
  # after plugin is loaded
  # Example: - test
  list:
  - Here list all
  - fireworks you
  - want to auto start
